# Generated by Django 5.2.6 on 2026-12-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstatus',
            name='name',
            field=models.CharField(choices=[('NEW', 'Новая'), ('ASSIGNED', 'Назначена'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Выполнена'), ('READY_FOR_PICKUP', 'Готова к выдаче'), ('CANCELED', 'Отменена')], max_length=20, unique=True),
        ),
    ]
