# Generated by Django 5.2.6 on 2026-12-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticketstatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Успешная попытка')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина неудачи')),
            ],
            options={
                'verbose_name': 'Попытка входа',
                'verbose_name_plural': 'Попытки входа',
                'ordering': ['-timestamp'],
            },
        ),
    ]
