# Generated by Django 5.2.8 on 2026-02-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_loginattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Login Attempt', 'verbose_name_plural': 'Login Attempts'},
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
