# Generated by Django 5.2.8 on 2026-02-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_loginattempt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Password Reset Code',
                'verbose_name_plural': 'Password Reset Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('laptop', 'Ноутбук'), ('desktop', 'Настольный компьютер'), ('phone', 'Телефон'), ('tablet', 'Планшет'), ('printer', 'Принтер'), ('other', 'Другое')], max_length=20),
        ),
    ]
